version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5555:5555"
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: consultant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
