"""Initial migration

Revision ID: 50ce0bb5e28d
Revises: 3649e7d96071
Create Date: 2024-01-16 14:40:45.897851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ce0bb5e28d'
down_revision = '3649e7d96071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infoCompany',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameCompany', sa.String(length=100), nullable=False),
    sa.Column('addUsers', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nameCompany')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.drop_table('infoCompany')
    # ### end Alembic commands ###
